apiVersion: v1
kind: Service
metadata:
  name: dubbo-consumer
  namespace: dubbo-demo
  labels:
    app: dubbo-consumer
spec:
  ports:
  - port: 80
    name: client
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: dubbo-consumer
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-consumer
  namespace: dubbo-demo
  labels:
    app: dubbo-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-consumer
  template:
    metadata:
      labels:
        app: dubbo-consumer
    spec:
      containers:
        - name: dubbo-consumer
          image: 192.168.1.231:5000/dubbo/dubbo-consumer:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 20
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
